retry = "5s"
max_stale = "10m"
log_level = "info"

template {
	source = "/etc/consul-template/templates/haproxy.cfg.ctmpl"
	destination = "/etc/haproxy/haproxy.cfg"
	command = "/usr/sbin/haproxy -D -p /var/run/haproxy.pid  -f /etc/haproxy/haproxy.cfg -sf $(cat /var/run/haproxy.pid) || true"
	perms = 0600
	backup = true
}

deduplicate {
  enabled = true
  prefix = "consul-template/dedup/"
}